# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "pip"
    directory: "/requirements.txt"
    schedule:
      interval: "daily"
